# Generated by Django 5.1.3 on 2024-11-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_order", models.CharField(max_length=100, unique=True)),
                ("date_of_purchase", models.DateTimeField()),
                ("customer_id", models.CharField(max_length=50)),
                ("item_code", models.CharField(max_length=50)),
            ],
        ),
    ]
